// src/components/Manage/TemplateViewModal.js
import React, { useState, useEffect } from 'react';

const TemplateViewModal = ({ isOpen, onClose, template }) => {
  const [activeTab, setActiveTab] = useState('content');
  const [copySuccess, setCopySuccess] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setActiveTab('content');
      setCopySuccess(false);
    }
  }, [isOpen]);

  if (!isOpen || !template) return null;

  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    const date = new Date(dateString + 'T00:00:00Z');
    const options = { year: 'numeric', month: 'short', day: 'numeric', timeZone: 'UTC' };
    return date.toLocaleDateString(undefined, options);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(template.textContent || '');
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error('Failed to copy text:', err);
    }
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    const content = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${template.name} - Print Version</title>
          <style>
            body { 
              font-family: Arial, sans-serif; 
              padding: 20px; 
              line-height: 1.6; 
            }
            .header { 
              border-bottom: 2px solid #333; 
              padding-bottom: 10px; 
              margin-bottom: 20px; 
            }
            .metadata { 
              background-color: #f5f5f5; 
              padding: 10px; 
              margin-bottom: 20px; 
              border-radius: 5px; 
            }
            .content { 
              white-space: pre-wrap; 
              font-family: 'Courier New', monospace; 
              background-color: #f9f9f9; 
              padding: 15px; 
              border: 1px solid #ddd; 
              border-radius: 5px; 
            }
            @media print {
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${template.name}</h1>
            <p>Template Type: ${template.type}</p>
          </div>
          <div class="metadata">
            <p><strong>Version:</strong> ${template.version}</p>
            <p><strong>Status:</strong> ${template.status}</p>
            <p><strong>Last Updated:</strong> ${formatDate(template.lastUpdated)}</p>
            ${template.generatedBy ? `<p><strong>Generated By:</strong> ${template.generatedBy}</p>` : ''}
          </div>
          <div class="content">
            ${template.textContent || 'No content available'}
          </div>
          <script>
            window.onload = function() { window.print(); window.close(); }
          </script>
        </body>
      </html>
    `;
    printWindow.document.write(content);
    printWindow.document.close();
  };

  const renderTemplateContent = () => {
    if (!template.textContent) {
      return (
        <div className="text-center py-8 text-gray-500">
          <p>No content available for this template.</p>
          {template.contentLink && (
            <a 
              href={template.contentLink} 
              target="_blank" 
              rel="noopener noreferrer"
              className="mt-2 inline-block text-blue-600 hover:text-blue-800"
            >
              Download Original File
            </a>
          )}
        </div>
      );
    }

    // Detect if it's a checklist based on content pattern
    const isChecklist = template.type.toLowerCase().includes('checklist') || 
                       template.textContent.includes('□') || 
                       template.textContent.includes('[ ]');

    if (isChecklist) {
      const lines = template.textContent.split('\n');
      return (
        <div className="space-y-2">
          {lines.map((line, index) => {
            const isCheckItem = line.trim().startsWith('□') || 
                               line.trim().startsWith('[ ]') || 
                               line.trim().startsWith('-');
            return (
              <div 
                key={index} 
                className={`${isCheckItem ? 'ml-4 flex items-start' : ''} ${line.trim() === '' ? 'h-4' : ''}`}
              >
                {isCheckItem && (
                  <span className="text-gray-400 mr-2 mt-0.5">□</span>
                )}
                <span className={`${!isCheckItem && line.trim() !== '' ? 'font-semibold' : ''}`}>
                  {line.replace(/^[\s□\[\]\-]+/, '')}
                </span>
              </div>
            );
          })}
        </div>
      );
    }

    // Regular document display
    return (
      <div className="whitespace-pre-wrap font-mono text-sm bg-gray-50 p-4 rounded-md border border-gray-200">
        {template.textContent}
      </div>
    );
  };

  return (
    <div className="fixed inset-0 bg-gray-600 bg-opacity-75 overflow-y-auto h-full w-full z-50 flex justify-center items-center p-4">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-4xl max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-200 flex justify-between items-center">
          <div>
            <h2 className="text-xl font-semibold text-gray-800">{template.name}</h2>
            <p className="text-sm text-gray-500 mt-1">{template.type}</p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="px-6 border-b border-gray-200">
          <nav className="-mb-px flex space-x-6">
            <button
              onClick={() => setActiveTab('content')}
              className={`py-3 px-1 border-b-2 font-medium text-sm focus:outline-none ${
                activeTab === 'content'
                  ? 'border-blue-500 text-blue-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              Content
            </button>
            <button
              onClick={() => setActiveTab('metadata')}
              className={`py-3 px-1 border-b-2 font-medium text-sm focus:outline-none ${
                activeTab === 'metadata'
                  ? 'border-blue-500 text-blue-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              Details
            </button>
          </nav>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {activeTab === 'content' ? (
            <div>{renderTemplateContent()}</div>
          ) : (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <h4 className="text-sm font-medium text-gray-500">Version</h4>
                  <p className="mt-1 text-sm text-gray-900">{template.version}</p>
                </div>
                <div>
                  <h4 className="text-sm font-medium text-gray-500">Status</h4>
                  <span className={`mt-1 inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                    template.status === 'Published' ? 'bg-green-100 text-green-800' :
                    template.status === 'Draft' ? 'bg-yellow-100 text-yellow-800' :
                    'bg-gray-100 text-gray-800'
                  }`}>
                    {template.status}
                  </span>
                </div>
                <div>
                  <h4 className="text-sm font-medium text-gray-500">Last Updated</h4>
                  <p className="mt-1 text-sm text-gray-900">{formatDate(template.lastUpdated)}</p>
                </div>
                <div>
                  <h4 className="text-sm font-medium text-gray-500">Template ID</h4>
                  <p className="mt-1 text-sm text-gray-900 font-mono">{template.id}</p>
                </div>
              </div>
              
              {template.generatedBy && (
                <div>
                  <h4 className="text-sm font-medium text-gray-500">Generated By</h4>
                  <p className="mt-1 text-sm text-gray-900">{template.generatedBy}</p>
                </div>
              )}
              
              {template.promptUsed && template.generatedBy?.includes('AI') && (
                <div>
                  <h4 className="text-sm font-medium text-gray-500">AI Prompt Used</h4>
                  <div className="mt-1 p-3 bg-gray-50 rounded-md">
                    <p className="text-sm text-gray-700 whitespace-pre-wrap">{template.promptUsed}</p>
                  </div>
                </div>
              )}

              {template.contentLink && (
                <div>
                  <h4 className="text-sm font-medium text-gray-500">Original File</h4>
                  <a 
                    href={template.contentLink} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="mt-1 inline-flex items-center text-sm text-blue-600 hover:text-blue-800"
                  >
                    <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Download
                  </a>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 border-t border-gray-200 flex justify-between items-center">
          <div className="flex space-x-3">
            <button
              onClick={handleCopy}
              className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-blue-500 flex items-center"
            >
              <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
              {copySuccess ? 'Copied!' : 'Copy Content'}
            </button>
            <button
              onClick={handlePrint}
              className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-blue-500 flex items-center"
            >
              <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
              </svg>
              Print
            </button>
          </div>
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-blue-500"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default TemplateViewModal;